### ISSUE TITLE
Game moves off of page when arrow keys are pressed

### ISSUE THREAD

**Issue by quamp** [bobatealee/scummoner#1]
Whenever I move the character around, the page moves along with it. Moving the character up or down will cause the game to scroll off the screen.

**Comment by bobatealee** [comment]
Hi, can I know what site you're playing on? What is your browser?

**Comment by quamp** [comment]
I am playing on Newgrounds, and the browser is Microsoft Edge. I've tried it on Google Chrome as well, it does the same thing. 
    On Saturday, May 11, 2024 at 07:48:52 PM CDT, Boba ***@***.***> wrote:  
 
 


Hi, can I know what site you're playing on? What is your browser?

**Comment by bobatealee** [comment]
Added some protections for this in 1.1.4.
